using System;
using System.Collections.Generic;
using System.Text;

namespace Stanz.Standard.Models.Other.SQL.BasicFinancials
{
    public class BasicFinancialInformationSql
    {
        public string Symbol { get; set; }
        public double? _10DayAverageTradingVolume { get; set; }
        public double? _13WeekPriceReturnDaily { get; set; }
        public double? _26WeekPriceReturnDaily { get; set; }
        public double? _3MonthAverageTradingVolume { get; set; }
        public double? _52WeekHigh { get; set; }
        public string _52WeekHighDate { get; set; }
        public double? _52WeekLow { get; set; }
        public string _52WeekLowDate { get; set; }
        public double? _52WeekPriceReturnDaily { get; set; }
        public double? _5DayPriceReturnDaily { get; set; }
        public double? AssetTurnoverAnnual { get; set; }
        public double? AssetTurnoverTTM { get; set; }
        public double? Beta { get; set; }
        public double? BookValuePerShareAnnual { get; set; }
        public double? BookValuePerShareQuarterly { get; set; }
        public double? BookValueShareGrowth5Y { get; set; }
        public double? CapitalSpendingGrowth5Y { get; set; }
        public double? CashFlowPerShareAnnual { get; set; }
        public double? CashFlowPerShareTTM { get; set; }
        public double? CashPerSharePerShareAnnual { get; set; }
        public double? CashPerSharePerShareQuarterly { get; set; }
        public double? CurrentDividendYieldTTM { get; set; }
        public double? CurrentEvFreeCashFlowAnnual { get; set; }
        public double? CurrentEvFreeCashFlowTTM { get; set; }
        public double? CurrentRatioAnnual { get; set; }
        public double? CurrentRatioQuarterly { get; set; }
        public double? DividendGrowthRate5Y { get; set; }
        public double? DividendPerShare5Y { get; set; }
        public double? DividendPerShareAnnual { get; set; }
        public double? DividendYield5Y { get; set; }
        public double? DividendYieldIndicatedAnnual { get; set; }
        public double? DividendsPerShareTTM { get; set; }
        public double? EbitdPerShareTTM { get; set; }
        public double? EbitdaCagr5Y { get; set; }
        public double? EbitdaobjecterimCagr5Y { get; set; }
        public double? EpsBasicExclExtraItemsAnnual { get; set; }
        public double? EpsBasicExclExtraItemsTTM { get; set; }
        public double? EpsExclExtraItemsAnnual { get; set; }
        public double? EpsExclExtraItemsTTM { get; set; }
        public double? EpsGrowth3Y { get; set; }
        public double? EpsGrowth5Y { get; set; }
        public double? EpsGrowthQuarterlyYoy { get; set; }
        public double? EpsGrowthTTMYoy { get; set; }
        public double? EpsInclExtraItemsAnnual { get; set; }
        public double? EpsInclExtraItemsTTM { get; set; }
        public double? EpsNormalizedAnnual { get; set; }
        public double? FocfCagr5Y { get; set; }
        public double? FreeCashFlowAnnual { get; set; }
        public double? FreeCashFlowPerShareTTM { get; set; }
        public double? FreeCashFlowTTM { get; set; }
        public double? FreeOperatingCashFlowRevenue5Y { get; set; }
        public double? FreeOperatingCashFlowRevenueTTM { get; set; }
        public double? GrossMargin5Y { get; set; }
        public double? GrossMarginAnnual { get; set; }
        public double? GrossMargobjectTM { get; set; }
        public double? InventoryTurnoverAnnual { get; set; }
        public double? InventoryTurnoverTTM { get; set; }
        public double? LongTermDebtEquityAnnual { get; set; }
        public double? LongTermDebtEquityQuarterly { get; set; }
        public double? MarketCapitalization { get; set; }
        public double? MonthToDatePriceReturnDaily { get; set; }
        public double? NetDebtAnnual { get; set; }
        public double? NetDebtobjecterim { get; set; }
        public double? NetIncomeEmployeeAnnual { get; set; }
        public double? NetIncomeEmployeeTTM { get; set; }
        public double? NetobjecterestCoverageAnnual { get; set; }
        public double? NetobjecterestCoverageTTM { get; set; }
        public double? NetMarginGrowth5Y { get; set; }
        public double? NetProfitMargin5Y { get; set; }
        public double? NetProfitMarginAnnual { get; set; }
        public double? NetProfitMargobjectTM { get; set; }
        public double? OperatingMargin5Y { get; set; }
        public double? OperatingMarginAnnual { get; set; }
        public double? OperatingMargobjectTM { get; set; }
        public double? PayoutRatioAnnual { get; set; }
        public double? PayoutRatioTTM { get; set; }
        public double? PbAnnual { get; set; }
        public double? PbQuarterly { get; set; }
        public double? PcfShareTTM { get; set; }
        public double? PeBasicExclExtraTTM { get; set; }
        public double? PeExclExtraAnnual { get; set; }
        public double? PeExclExtraHighTTM { get; set; }
        public double? PeExclExtraTTM { get; set; }
        public double? PeExclLowTTM { get; set; }
        public double? PeInclExtraTTM { get; set; }
        public double? PeNormalizedAnnual { get; set; }
        public double? PfcfShareAnnual { get; set; }
        public double? PfcfShareTTM { get; set; }
        public double? PretaxMargin5Y { get; set; }
        public double? PretaxMarginAnnual { get; set; }
        public double? PretaxMargobjectTM { get; set; }
        public double? PriceRelativeToSP50013Week { get; set; }
        public double? PriceRelativeToSP50026Week { get; set; }
        public double? PriceRelativeToSP5004Week { get; set; }
        public double? PriceRelativeToSP50052Week { get; set; }
        public double? PriceRelativeToSP500Ytd { get; set; }
        public double? PsAnnual { get; set; }
        public double? PsTTM { get; set; }
        public double? PtbvAnnual { get; set; }
        public double? PtbvQuarterly { get; set; }
        public double? QuickRatioAnnual { get; set; }
        public double? QuickRatioQuarterly { get; set; }
        public double? ReceivablesTurnoverAnnual { get; set; }
        public double? ReceivablesTurnoverTTM { get; set; }
        public double? RevenueEmployeeAnnual { get; set; }
        public double? RevenueEmployeeTTM { get; set; }
        public double? RevenueGrowth3Y { get; set; }
        public double? RevenueGrowth5Y { get; set; }
        public double? RevenueGrowthQuarterlyYoy { get; set; }
        public double? RevenueGrowthTTMYoy { get; set; }
        public double? RevenuePerShareAnnual { get; set; }
        public double? RevenuePerShareTTM { get; set; }
        public double? RevenueShareGrowth5Y { get; set; }
        public double? RoaRfy { get; set; }
        public double? Roaa5Y { get; set; }
        public double? Roae5Y { get; set; }
        public double? RoaeTTM { get; set; }
        public double? RoeRfy { get; set; }
        public double? RoeTTM { get; set; }
        public double? Roi5Y { get; set; }
        public double? RoiAnnual { get; set; }
        public double? RoiTTM { get; set; }
        public double? TangibleBookValuePerShareAnnual { get; set; }
        public double? TangibleBookValuePerShareQuarterly { get; set; }
        public double? TbvCagr5Y { get; set; }
        public double? TotalDebtTotalEquityAnnual { get; set; }
        public double? TotalDebtTotalEquityQuarterly { get; set; }
        public double? TotalDebtCagr5Y { get; set; }
        public double? YearToDatePriceReturnDaily { get; set; }
    }
}
